theme = "modus_operandi_tinted"

[editor]
mouse = false

[keys.normal]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[editor.file-picker]
hidden = false

