[[language]]
name = "scheme"
scope = "source.scheme"
injection-regex = "scheme"
file-types = ["ss", "scm"]
shebangs = ["scheme", "guile"]
comment-token = ";"
language-servers = [ "guile-lsp" ]

[language-server.guile-lsp]
command = "guile-lsp-server"
args = ["--stdio"]
